# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e4eb1a15d395fa37f9ec046ba1732d707eb935add42a36b7c81227d97f54c8985931da6b01d04dc38cd1c74c52eaa14fbad51da8679950c79297fdcad54bdf

test:
  secret_key_base: a70c141f31e3513950e0e31cf7aff4313c3bf71f8fc618dba7aef42ee530f883b854c763b6e5ff9673bc82330e224ac694d6c8074ef02efeca3166b133215893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
